/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Mariano
 */

import Logica.ABMCliente;
import Datos.Cliente;
import Datos.Comida;
import Datos.DetallePedido;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Datos.Pedido;
import Datos.Zona;
import Logica.ABMComida;
import Logica.ABMPedido;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class DatosPedido extends javax.swing.JFrame {

    /**
     * Creates new form DatosPedido
     */
    private java.sql.Statement sentencia;
    private ResultSet rsDatos;
    private float total;
    private int numLinea;
    private ArrayList<DetallePedido> listaDetallePedido;
    private ArrayList<Zona> listaZonas;
    private Cliente Cl;
    
    public DatosPedido() throws ClassNotFoundException, SQLException {
        initComponents();
        total = 0;
        listaDetallePedido = new ArrayList<DetallePedido>();
        listaZonas = new ArrayList<Zona>();
        Cl = new Cliente();
        setLocationRelativeTo(null);
        Date d = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = formatoFecha.format(d);
        jLabelMostrarFecha.setText(fecha);
        cargarJComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPedidoNum = new javax.swing.JLabel();
        jLabelMostrarPedidoNum = new javax.swing.JLabel();
        jLabelMostrarHora = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelMostrarFecha = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jPanelCliente = new javax.swing.JPanel();
        jPanelBuscarCliente = new javax.swing.JPanel();
        jLabelBuscarTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelMensajeExistenciaCliente = new javax.swing.JLabel();
        jButtonNuevoCliente = new javax.swing.JButton();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelApeNom = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabelLugarEnvio = new javax.swing.JLabel();
        jLabelZona = new javax.swing.JLabel();
        jLabelImporteEnvio = new javax.swing.JLabel();
        jLabelMostrarApeNom = new javax.swing.JLabel();
        jLabelMostrarTelefono = new javax.swing.JLabel();
        jLabelMostrarDomicilio = new javax.swing.JLabel();
        jTextFieldLugarDeEnvio = new javax.swing.JTextField();
        jComboBoxZona = new javax.swing.JComboBox<>();
        jLabelMostrarImporte = new javax.swing.JLabel();
        jPanelDatosPedido = new javax.swing.JPanel();
        jLabelComida = new javax.swing.JLabel();
        jComboBoxSeleccionarComida = new javax.swing.JComboBox<>();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPaneDetallePedido = new javax.swing.JScrollPane();
        jTableDetallesPedido = new javax.swing.JTable();
        jButtonEliminar = new javax.swing.JButton();
        jLabelImporteTotal = new javax.swing.JLabel();
        jLabelMostrarImporteTotal = new javax.swing.JLabel();
        jButtonConfirmarPedido = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FastFoodSystem - Datos del Pedido");
        setMaximumSize(new java.awt.Dimension(700, 470));
        setMinimumSize(new java.awt.Dimension(700, 470));
        setResizable(false);

        jLabelPedidoNum.setText("Pedido Número:");

        jLabelMostrarPedidoNum.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelMostrarPedidoNum.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabelMostrarPedidoNum.setPreferredSize(new java.awt.Dimension(100, 14));

        jLabelMostrarHora.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabelMostrarHora.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabelMostrarHora.setPreferredSize(new java.awt.Dimension(60, 14));

        jLabelHora.setText("Hora:");

        jLabelMostrarFecha.setMaximumSize(new java.awt.Dimension(85, 14));
        jLabelMostrarFecha.setMinimumSize(new java.awt.Dimension(85, 14));
        jLabelMostrarFecha.setPreferredSize(new java.awt.Dimension(85, 14));

        jLabelFecha.setText("Fecha:");

        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanelCliente.setMaximumSize(new java.awt.Dimension(610, 170));
        jPanelCliente.setMinimumSize(new java.awt.Dimension(610, 170));
        jPanelCliente.setPreferredSize(new java.awt.Dimension(610, 170));

        jPanelBuscarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanelBuscarCliente.setMaximumSize(new java.awt.Dimension(300, 75));
        jPanelBuscarCliente.setMinimumSize(new java.awt.Dimension(300, 75));

        jLabelBuscarTelefono.setText("Teléfono:");

        jTextFieldTelefono.setMaximumSize(new java.awt.Dimension(120, 20));
        jTextFieldTelefono.setMinimumSize(new java.awt.Dimension(120, 20));

        jButtonBuscar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(75, 23));
        jButtonBuscar.setMinimumSize(new java.awt.Dimension(75, 23));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarClienteLayout = new javax.swing.GroupLayout(jPanelBuscarCliente);
        jPanelBuscarCliente.setLayout(jPanelBuscarClienteLayout);
        jPanelBuscarClienteLayout.setHorizontalGroup(
            jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelBuscarClienteLayout.setVerticalGroup(
            jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabelMensajeExistenciaCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMensajeExistenciaCliente.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMensajeExistenciaCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensajeExistenciaCliente.setMaximumSize(new java.awt.Dimension(175, 25));
        jLabelMensajeExistenciaCliente.setMinimumSize(new java.awt.Dimension(175, 25));
        jLabelMensajeExistenciaCliente.setPreferredSize(new java.awt.Dimension(175, 25));

        jButtonNuevoCliente.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonNuevoCliente.setText("Nuevo Cliente");
        jButtonNuevoCliente.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonNuevoCliente.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonNuevoCliente.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoClienteActionPerformed(evt);
            }
        });

        jLabelTelefono.setText("Teléfono:");

        jLabelApeNom.setText("Apellido y Nombre:");

        jLabelDomicilio.setText("Domicilio:");

        jLabelLugarEnvio.setText("Lugar de Envio:");

        jLabelZona.setText("Zona:");

        jLabelImporteEnvio.setText("Importe de Envío:");

        jLabelMostrarApeNom.setMaximumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarApeNom.setMinimumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarApeNom.setPreferredSize(new java.awt.Dimension(150, 14));

        jLabelMostrarTelefono.setMaximumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarTelefono.setMinimumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarTelefono.setPreferredSize(new java.awt.Dimension(150, 14));

        jLabelMostrarDomicilio.setMaximumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarDomicilio.setMinimumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarDomicilio.setPreferredSize(new java.awt.Dimension(150, 14));

        jTextFieldLugarDeEnvio.setMaximumSize(new java.awt.Dimension(150, 20));
        jTextFieldLugarDeEnvio.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldLugarDeEnvio.setPreferredSize(new java.awt.Dimension(150, 20));

        jComboBoxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Zona", " " }));
        jComboBoxZona.setMaximumSize(new java.awt.Dimension(150, 20));
        jComboBoxZona.setMinimumSize(new java.awt.Dimension(150, 20));
        jComboBoxZona.setPreferredSize(new java.awt.Dimension(150, 20));
        jComboBoxZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZonaActionPerformed(evt);
            }
        });

        jLabelMostrarImporte.setMaximumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarImporte.setMinimumSize(new java.awt.Dimension(150, 14));
        jLabelMostrarImporte.setPreferredSize(new java.awt.Dimension(150, 14));

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelMensajeExistenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApeNom)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabelDomicilio)
                    .addComponent(jLabelLugarEnvio)
                    .addComponent(jLabelZona)
                    .addComponent(jLabelImporteEnvio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMostrarImporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMostrarApeNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMostrarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMostrarDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLugarDeEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addComponent(jPanelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMensajeExistenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabelMostrarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApeNom)
                    .addComponent(jLabelMostrarApeNom, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDomicilio)
                    .addComponent(jLabelMostrarDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLugarEnvio)
                    .addComponent(jTextFieldLugarDeEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZona)
                    .addComponent(jComboBoxZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImporteEnvio)
                    .addComponent(jLabelMostrarImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDatosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanelDatosPedido.setMaximumSize(new java.awt.Dimension(610, 200));
        jPanelDatosPedido.setMinimumSize(new java.awt.Dimension(610, 200));
        jPanelDatosPedido.setPreferredSize(new java.awt.Dimension(610, 200));

        jLabelComida.setText("Comida:");

        jComboBoxSeleccionarComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Comida", "Pizza Especial", "Pizza Cuatro Quesos", "Lomito Completo", "Empanada", "Papas Fritas" }));
        jComboBoxSeleccionarComida.setMaximumSize(new java.awt.Dimension(150, 20));
        jComboBoxSeleccionarComida.setMinimumSize(new java.awt.Dimension(150, 20));
        jComboBoxSeleccionarComida.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabelCantidad.setText("Cantidad:");

        jTextFieldCantidad.setMaximumSize(new java.awt.Dimension(100, 20));
        jTextFieldCantidad.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextFieldCantidad.setPreferredSize(new java.awt.Dimension(100, 20));

        jButtonAgregar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jTableDetallesPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio Unitario", "Precio Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDetallePedido.setViewportView(jTableDetallesPedido);
        if (jTableDetallesPedido.getColumnModel().getColumnCount() > 0) {
            jTableDetallesPedido.getColumnModel().getColumn(0).setResizable(false);
            jTableDetallesPedido.getColumnModel().getColumn(1).setResizable(false);
            jTableDetallesPedido.getColumnModel().getColumn(2).setResizable(false);
            jTableDetallesPedido.getColumnModel().getColumn(3).setResizable(false);
            jTableDetallesPedido.getColumnModel().getColumn(4).setResizable(false);
        }

        jButtonEliminar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelImporteTotal.setText("Importe Total: $");

        jLabelMostrarImporteTotal.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelMostrarImporteTotal.setMinimumSize(new java.awt.Dimension(100, 14));
        jLabelMostrarImporteTotal.setPreferredSize(new java.awt.Dimension(100, 14));

        javax.swing.GroupLayout jPanelDatosPedidoLayout = new javax.swing.GroupLayout(jPanelDatosPedido);
        jPanelDatosPedido.setLayout(jPanelDatosPedidoLayout);
        jPanelDatosPedidoLayout.setHorizontalGroup(
            jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelImporteTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMostrarImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar))
                    .addComponent(jScrollPaneDetallePedido)
                    .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                        .addComponent(jLabelComida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSeleccionarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButtonAgregar)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelDatosPedidoLayout.setVerticalGroup(
            jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComida)
                    .addComponent(jComboBoxSeleccionarComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneDetallePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonEliminar))
                    .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMostrarImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImporteTotal))))
                .addContainerGap())
        );

        jButtonConfirmarPedido.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonConfirmarPedido.setText("Confirmar Pedido");
        jButtonConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarPedidoActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPedidoNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMostrarPedidoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMostrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMostrarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                            .addComponent(jPanelDatosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmarPedido)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMostrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHora)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelMostrarHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPedidoNum)
                            .addComponent(jLabelMostrarPedidoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmarPedido)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        Cliente C = new Cliente();
        try {
            C = buscarCliente(Integer.parseInt(jTextFieldTelefono.getText()));
            if(C!=null){
                jLabelMostrarTelefono.setText(String.valueOf(C.getTelefono()));
                jLabelMostrarApeNom.setText(C.getApellido() + " " + C.getNombre());
                jLabelMostrarDomicilio.setText(C.getDomicilio());
                jLabelMensajeExistenciaCliente.setText("");
            }
            else{
                jLabelMensajeExistenciaCliente.setText("Cliente Inexistente");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatosPedido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DatosPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZonaActionPerformed
        // TODO add your handling code here:
        switch(String.valueOf(jComboBoxZona.getSelectedItem())){
            case "Centro":
                jLabelMostrarImporte.setText(String.valueOf(listaZonas.get(0).getPrecio()));
                break;
            case "Norte":
                jLabelMostrarImporte.setText(String.valueOf(listaZonas.get(1).getPrecio()));
                break;
            case "Sur":
                jLabelMostrarImporte.setText(String.valueOf(listaZonas.get(2).getPrecio()));
                break;
            case "Este":
                jLabelMostrarImporte.setText(String.valueOf(listaZonas.get(3).getPrecio()));
                break;
            case "Oeste":
                jLabelMostrarImporte.setText(String.valueOf(listaZonas.get(4).getPrecio()));
                break;
        }
    }//GEN-LAST:event_jComboBoxZonaActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        String[] datos = new String[5];
        DefaultTableModel dtm = (DefaultTableModel)jTableDetallesPedido.getModel();
        try {
            DetallePedido DP = new DetallePedido();
            ABMComida ABMC = new ABMComida();
            Comida C = new Comida();
            C = ABMC.buscarComida(String.valueOf(jComboBoxSeleccionarComida.getSelectedItem()));
            DP.setCantidad(Integer.parseInt(jTextFieldCantidad.getText()));
            DP.setIdComida(C.getIdComida());
            DP.setNumLinea(numLinea + 1);
            listaDetallePedido.add(DP);
            datos[0] = String.valueOf(C.getIdComida());
            datos[1] = C.getDescripcion();
            datos[2] = jTextFieldCantidad.getText();
            datos[3] = String.valueOf(C.getPrecio());
            datos[4] = String.valueOf(Float.parseFloat(datos[3]) * Float.parseFloat(jTextFieldCantidad.getText()));
            total = total + Float.parseFloat(datos[4]);
            dtm.addRow(datos);
            jLabelMostrarImporteTotal.setText(String.valueOf(total));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DatosPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarPedidoActionPerformed
        // TODO add your handling code here:
        Pedido P = new Pedido();
        Cliente C = new Cliente();
        ABMPedido ABMP = new ABMPedido();
        java.util.Date FP = new java.util.Date();
        try {
            if(Cl.isEstado()){
                
            }
            else{
                C = buscarCliente(Long.parseLong(jTextFieldTelefono.getText()));
                P.setIdCliente(C.getIdCliente());
                P.setEstado(0);
                java.sql.Date fecha = new java.sql.Date(FP.getTime());
                P.setFecha(fecha);
                java.sql.Time hora = new java.sql.Time(FP.getTime());
                P.setHora(hora);
                P.setLugarDeEnvio(jTextFieldLugarDeEnvio.getText());
                P.setZona(String.valueOf(jComboBoxZona.getSelectedItem()));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DatosPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConfirmarPedido CP = new ConfirmarPedido();
        CP.setP(P);
        CP.setDP(listaDetallePedido);
        CP.setVisible(true);
    }//GEN-LAST:event_jButtonConfirmarPedidoActionPerformed
    
    private void jButtonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoClienteActionPerformed
        // TODO add your handling code here:
        VentanaClientes C = new VentanaClientes();
        C.setVisible(true);
    }//GEN-LAST:event_jButtonNuevoClienteActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTableDetallesPedido.getModel();
        int fila = jTableDetallesPedido.getSelectedRow();
        if (fila >= 0) {
            int filasselec[]  = jTableDetallesPedido.getSelectedRows();
            for (int i=0; i<filasselec.length;i++){
                total = total - Float.parseFloat(String.valueOf(modelo.getValueAt(filasselec[i], 4)));
                jLabelMostrarImporteTotal.setText(String.valueOf(total));
                modelo.removeRow(filasselec[i]-i);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No Selecciono Ninguna Fila", "Fast Food System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public Cliente buscarCliente(long telefono) throws ClassNotFoundException, SQLException{
        ABMCliente ABMC = new ABMCliente();
        Cliente C = new Cliente();
        C = ABMC.buscarCliente(telefono);
        return C;
    }
    
    public void mostrarTablaModificar(int cod, long telefono) throws ClassNotFoundException, SQLException{
        //Cliente C = new Cliente();
        Pedido P = new Pedido();
        Comida Co = new Comida();
        DefaultTableModel modelo = (DefaultTableModel) jTableDetallesPedido.getModel();
        String[] datos = new String[5];
        ABMPedido ABMP = new ABMPedido();
        ABMComida ABMCo = new ABMComida();
        ArrayList<DetallePedido> listaDetallePedido = new ArrayList<DetallePedido>();
        P = ABMP.buscarPedido(cod);
        Cl = buscarCliente(telefono);
        listaDetallePedido = ABMP.buscarDetallePedido(P.getIdPedido());
        if(Cl!=null){
            jLabelMostrarTelefono.setText(String.valueOf(Cl.getTelefono()));
            jLabelMostrarApeNom.setText(Cl.getApellido() + " " + Cl.getNombre());
            jLabelMostrarDomicilio.setText(Cl.getDomicilio());
            jTextFieldLugarDeEnvio.setText(P.getLugarDeEnvio());
            for(int i = 0; i<listaDetallePedido.size(); i++){
                Co = ABMCo.buscarComidaId(listaDetallePedido.get(i).getIdComida());
                datos[0] = String.valueOf(listaDetallePedido.get(i).getIdComida());
                datos[1] = Co.getDescripcion();
                datos[2] = String.valueOf(listaDetallePedido.get(i).getCantidad());
                datos[3] = String.valueOf(Co.getPrecio());
                datos[4] = String.valueOf(Float.parseFloat(datos[3]) * Float.parseFloat(String.valueOf(listaDetallePedido.get(i).getCantidad())));
                total = total + Float.parseFloat(datos[4]);
                modelo.addRow(datos);
                jLabelMostrarImporteTotal.setText(String.valueOf(total));
            }
            
        }  
    }
    
    public void cargarJComboBox() throws ClassNotFoundException, SQLException{
        ABMPedido ABMP = new ABMPedido();
        listaZonas = ABMP.buscarZona();
        for(int i = 0; i<listaZonas.size(); i++){
            jComboBoxZona.addItem(listaZonas.get(i).getDescripcion());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                try {
                    new DatosPedido().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DatosPedido.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DatosPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmarPedido;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonNuevoCliente;
    private javax.swing.JComboBox<String> jComboBoxSeleccionarComida;
    private javax.swing.JComboBox<String> jComboBoxZona;
    private javax.swing.JLabel jLabelApeNom;
    private javax.swing.JLabel jLabelBuscarTelefono;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelImporteEnvio;
    private javax.swing.JLabel jLabelImporteTotal;
    private javax.swing.JLabel jLabelLugarEnvio;
    private javax.swing.JLabel jLabelMensajeExistenciaCliente;
    private javax.swing.JLabel jLabelMostrarApeNom;
    private javax.swing.JLabel jLabelMostrarDomicilio;
    private javax.swing.JLabel jLabelMostrarFecha;
    private javax.swing.JLabel jLabelMostrarHora;
    private javax.swing.JLabel jLabelMostrarImporte;
    private javax.swing.JLabel jLabelMostrarImporteTotal;
    private javax.swing.JLabel jLabelMostrarPedidoNum;
    private javax.swing.JLabel jLabelMostrarTelefono;
    private javax.swing.JLabel jLabelPedidoNum;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelZona;
    private javax.swing.JPanel jPanelBuscarCliente;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelDatosPedido;
    private javax.swing.JScrollPane jScrollPaneDetallePedido;
    private javax.swing.JTable jTableDetallesPedido;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldLugarDeEnvio;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
