/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Datos.Comida;
import Logica.ABMComida;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Gonzalez
 */
public class GestionarComida extends javax.swing.JFrame {

    /**
     * Creates new form GestionarComida
     */
    public GestionarComida() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDescComida = new javax.swing.JPanel();
        jLabelDescripcionComida = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jButtonNuevaComida = new javax.swing.JButton();
        jButtonEliminarComida = new javax.swing.JButton();
        jButtonModificarComida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableComida = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Comida");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanelDescComida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Comida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        jLabelDescripcionComida.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDescripcionComida.setText("Descripción:");

        jTextFieldDescripcion.setMaximumSize(new java.awt.Dimension(210, 20));
        jTextFieldDescripcion.setMinimumSize(new java.awt.Dimension(210, 20));
        jTextFieldDescripcion.setPreferredSize(new java.awt.Dimension(210, 20));
        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDescComidaLayout = new javax.swing.GroupLayout(jPanelDescComida);
        jPanelDescComida.setLayout(jPanelDescComidaLayout);
        jPanelDescComidaLayout.setHorizontalGroup(
            jPanelDescComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescComidaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelDescripcionComida)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanelDescComidaLayout.setVerticalGroup(
            jPanelDescComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescComidaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelDescComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcionComida)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonNuevaComida.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonNuevaComida.setText("Nueva Comida");
        jButtonNuevaComida.setMaximumSize(new java.awt.Dimension(71, 25));
        jButtonNuevaComida.setMinimumSize(new java.awt.Dimension(71, 25));
        jButtonNuevaComida.setPreferredSize(new java.awt.Dimension(71, 25));
        jButtonNuevaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaComidaActionPerformed(evt);
            }
        });

        jButtonEliminarComida.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonEliminarComida.setText("Eliminar Comida");
        jButtonEliminarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarComidaActionPerformed(evt);
            }
        });

        jButtonModificarComida.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonModificarComida.setText("Modificar Comida");
        jButtonModificarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarComidaActionPerformed(evt);
            }
        });

        jTableComida.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableComida);

        jButtonSalir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setMaximumSize(new java.awt.Dimension(71, 25));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(71, 25));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(71, 25));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addComponent(jPanelDescComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelError)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonEliminarComida))
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDescComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabelError)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarComida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaComidaActionPerformed
        Comidas C = new Comidas();
        C.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButtonNuevaComidaActionPerformed

    private void jButtonEliminarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarComidaActionPerformed
        Comidas C = new Comidas();
        C.setVisible(true);
    }//GEN-LAST:event_jButtonEliminarComidaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
       ABMComida BC = new ABMComida();
        Comida C = new Comida();
        try {
            C = BC.buscarComida(jTextFieldDescripcion.getText());
            if(C != null){
            Comidas VC = new Comidas();
            VC.setDatosComida(C);
            VC.setCondatos_vacio(1); // 1 por que va con datos 
            VC.LlenarCampos();
            VC.setVisible(true);
            this.dispose();
            }
            else
            {
                jLabelError.setText("Comida Inexistente!");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GestionarComida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionarComida.class.getName()).log(Level.SEVERE, null, ex);
    }      
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jButtonModificarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarComidaActionPerformed
        Comidas C = new Comidas();
        C.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButtonModificarComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarComida;
    private javax.swing.JButton jButtonModificarComida;
    private javax.swing.JButton jButtonNuevaComida;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDescripcionComida;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JPanel jPanelDescComida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableComida;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
