/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Usuario;
import Logica.ABMUsuario;
import Logica.OperacionesTransacciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gonzalez
 */
public class Usuarios extends javax.swing.JFrame {

    private Usuario datosUsuario;
    private int condatos_vacio;
    private String nombreUsu;
    ResultSet R;
    Usuario usuarioSistema;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTipoDocu();
        cargarTipoUsuario();
        usuarioSistema = new Usuario();
    }

    public Usuario getUsuarioSistema() {
        return usuarioSistema;
    }

    public void setUsuarioSistema(Usuario usuarioSistema) {
        this.usuarioSistema = usuarioSistema;
    }

    public Usuario getDatosUsuario() {
        return datosUsuario;
    }

    public void setDatosUsuario(Usuario datosUsuario) {
        this.datosUsuario = datosUsuario;
    }

    public int getCondatos_vacio() {
        return condatos_vacio;
    }

    public void setCondatos_vacio(int condatos_vacio) {
        this.condatos_vacio = condatos_vacio;
    }

    public String getNombreUsu() {
        return nombreUsu;
    }

    public void setNombreUsu(String nombUsu) {
        this.nombreUsu = nombUsu;
    }

    void LlenarCampos(int boton) throws SQLException {

        switch (boton) {
            //nuevo usuario
            case 1:
                jButtonEliminar.setEnabled(false);
                jButtonGuardar.setEnabled(true);
                break;
            //eliminar usuario
            case 2:
                jButtonEliminar.setEnabled(true);
                jButtonGuardar.setEnabled(false);
                jTextFieldNombUsu.setEditable(false);
                jTextFieldNombApe.setEditable(false);
                jPasswordContra.setEditable(false);
                jComboBoxTipoDocu.setEnabled(false);
                jTextFieldNumDocu.setEnabled(false);
                jComboBoxTipoUsu.setEnabled(false);
                break;
            //modificar usuario
            case 3:
                jButtonEliminar.setEnabled(false);
                jButtonGuardar.setEnabled(true);
                break;
        }

        if (condatos_vacio == 1) {
            jLabelIdUsu.setText(String.valueOf(datosUsuario.getIdUsuario()));
            jTextFieldNombUsu.setText(datosUsuario.getNombreUsuario());
            jTextFieldNombApe.setText(datosUsuario.getNombreYApellido());
            jPasswordContra.setText(datosUsuario.getContraseña());
            jComboBoxTipoDocu.setSelectedIndex(Integer.parseInt(datosUsuario.getTipoDocumento()));
            jTextFieldNumDocu.setText(String.valueOf(datosUsuario.getNumDocumento()));
            jComboBoxTipoUsu.setSelectedIndex(datosUsuario.getTipoUsuario());
        } else {
            Usuario U = new Usuario();
            try {
                jLabelIdUsu.setText(String.valueOf(U.obtenerSiguienteId()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTextFieldNombUsu.setText(getNombreUsu());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jLabelNombUsu = new javax.swing.JLabel();
        jLabelNombApe = new javax.swing.JLabel();
        jLabeContra = new javax.swing.JLabel();
        jLabelIdUsu = new javax.swing.JLabel();
        jTextFieldNombUsu = new javax.swing.JTextField();
        jTextFieldNombApe = new javax.swing.JTextField();
        jComboBoxTipoUsu = new javax.swing.JComboBox();
        jLabelError = new javax.swing.JLabel();
        jLabelTipoDocu = new javax.swing.JLabel();
        jLabelNroDocu = new javax.swing.JLabel();
        jLabelTipoUsu = new javax.swing.JLabel();
        jTextFieldNumDocu = new javax.swing.JTextField();
        jPasswordContra = new javax.swing.JPasswordField();
        jComboBoxTipoDocu = new javax.swing.JComboBox();
        jButtonEliminar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        jLabelIdUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelIdUsuario.setText("Id Usuario:");

        jLabelNombUsu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombUsu.setText("Nombre de Usuario:");

        jLabelNombApe.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombApe.setText("Nombre y Apellido:");

        jLabeContra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabeContra.setText("Contraseña:");

        jLabelIdUsu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelIdUsu.setText("9999999999");

        jTextFieldNombUsu.setMaximumSize(new java.awt.Dimension(210, 20));
        jTextFieldNombUsu.setMinimumSize(new java.awt.Dimension(210, 20));
        jTextFieldNombUsu.setPreferredSize(new java.awt.Dimension(210, 20));

        jTextFieldNombApe.setMaximumSize(new java.awt.Dimension(210, 20));
        jTextFieldNombApe.setMinimumSize(new java.awt.Dimension(210, 20));
        jTextFieldNombApe.setPreferredSize(new java.awt.Dimension(210, 20));

        jComboBoxTipoUsu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un tipo de usuario..." }));
        jComboBoxTipoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoUsuActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        jLabelTipoDocu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTipoDocu.setText("Tipo de Documento:");

        jLabelNroDocu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNroDocu.setText("Nro de Documento:");

        jLabelTipoUsu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTipoUsu.setText("Tipo de Usuario");

        jTextFieldNumDocu.setMaximumSize(new java.awt.Dimension(210, 20));
        jTextFieldNumDocu.setMinimumSize(new java.awt.Dimension(210, 20));
        jTextFieldNumDocu.setPreferredSize(new java.awt.Dimension(210, 20));

        jPasswordContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordContraActionPerformed(evt);
            }
        });

        jComboBoxTipoDocu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un tipo de documento..." }));
        jComboBoxTipoDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDocuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addGap(107, 107, 107))
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jLabelTipoUsu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxTipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jLabelNroDocu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNumDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombUsu)
                            .addComponent(jLabelIdUsuario))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdUsu)
                            .addComponent(jTextFieldNombUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombApe)
                            .addComponent(jLabeContra)
                            .addComponent(jLabelTipoDocu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNombApe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPasswordContra)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdUsuario)
                    .addComponent(jLabelIdUsu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombUsu)
                    .addComponent(jTextFieldNombUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombApe)
                    .addComponent(jTextFieldNombApe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeContra)
                    .addComponent(jPasswordContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDocu)
                    .addComponent(jComboBoxTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNroDocu)
                    .addComponent(jTextFieldNumDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoUsu)
                    .addComponent(jComboBoxTipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addContainerGap())
        );

        jButtonEliminar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-eliminar-comida.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonEliminar.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonGuardar.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoUsuActionPerformed

    }//GEN-LAST:event_jComboBoxTipoUsuActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        GestionarUsuario volverGestionarUsuario = new GestionarUsuario();
        volverGestionarUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        OperacionesTransacciones OT = new OperacionesTransacciones();
        int accion = 12;
        int entidad = 2;
        Usuario U = new Usuario();
        try {
            U.eliminar(Integer.parseInt(jLabelIdUsu.getText()));
            OT.registrarTransaccion(accion, entidad, Integer.parseInt(jLabelIdUsu.getText()), usuarioSistema);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "El Usuario Se Elimino Correctamente", "FastFoodSystem", JOptionPane.INFORMATION_MESSAGE);
        GestionarUsuario volverGestionarUsuario = new GestionarUsuario();
        volverGestionarUsuario.setUsuarioSistema(usuarioSistema);
        volverGestionarUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        OperacionesTransacciones OT = new OperacionesTransacciones();
        int accion;
        int entidad = 2;
        if (((((validarCampoNombreUsuario() && validarCampoNombreApellido()) && validarCampoContraseña()) && validarTipoDocu())
                && validarNumeroDocu()) && validarTipoUsuario()) {
            Usuario U = new Usuario();
            U.setIdUsuario(Integer.parseInt(jLabelIdUsu.getText()));
            U.setNombreUsuario(jTextFieldNombUsu.getText());
            U.setNombreYApellido(jTextFieldNombApe.getText());
            U.setContraseña(jPasswordContra.getText());
            U.setTipoDocumento(String.valueOf(jComboBoxTipoDocu.getSelectedIndex()));
            U.setNumDocumento(Integer.parseInt(jTextFieldNumDocu.getText()));
            U.setTipoUsuario(jComboBoxTipoUsu.getSelectedIndex());
            ABMUsuario ABMU = new ABMUsuario();
            if (condatos_vacio != 1) {
                try {
                    if (ABMU.modificarUsuario(U)) {
                        accion = 13;
                        OT.registrarTransaccion(accion, entidad, Integer.parseInt(jLabelIdUsu.getText()), usuarioSistema);
                        JOptionPane.showMessageDialog(this, "El Usuario Se Cargo Correctamente", "FastFoodSystem", JOptionPane.INFORMATION_MESSAGE);
                        GestionarUsuario volverGestionarUsuario = new GestionarUsuario();
                        volverGestionarUsuario.setUsuarioSistema(usuarioSistema);
                        volverGestionarUsuario.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "ERROR: El Usuario Ya Existe", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);

                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    if (ABMU.nuevoUsuario(U)) {
                        JOptionPane.showMessageDialog(this, "ERROR: El Nombre De Usuario Pertenece A Otro Usuario", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "El Usuario Se Modifico Correctamente", "FastFoodSystem", JOptionPane.INFORMATION_MESSAGE);
                        accion = 11;
                        OT.registrarTransaccion(accion, entidad, Integer.parseInt(jLabelIdUsu.getText()), usuarioSistema);
                        GestionarUsuario volverGestionarUsuario = new GestionarUsuario();
                        volverGestionarUsuario.setUsuarioSistema(usuarioSistema);
                        volverGestionarUsuario.setVisible(true);
                        this.dispose();
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void cargarTipoDocu() {
        try {
            Usuario U = new Usuario();
            R = U.consultaTipoDocu();
            try {
                while (R.next()) {
                    jComboBoxTipoDocu.addItem(R.getObject("tipoDocumento"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarTipoUsuario() {
        try {
            Usuario U = new Usuario();
            R = U.consultaTipoUsuario();
            try {
                while (R.next()) {
                    jComboBoxTipoUsu.addItem(R.getObject("tipoUsuario"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validarCampoNombreUsuario() {
        if (jTextFieldNombUsu.getText().length() > 0) {
            if (jTextFieldNombUsu.getText().length() <= 20) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre de Usuario\" No Debe Contener Mas de 20 Caracteres", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre de Usuario\" No Debe Estar Vacio", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }

    private boolean validarCampoNombreApellido() {
        if (jTextFieldNombApe.getText().length() > 0) {
            if (jTextFieldNombApe.getText().length() <= 40) {
                if (jTextFieldNombApe.getText().matches("[A-Za-z\\s]+")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre y Apellido\" Debe Contener Solo Letras", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre y Apellido\" No Debe Contener Mas de 40 Caracteres", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre y Apellido\" No Debe Estar Vacio", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validarCampoContraseña() {
        if (jPasswordContra.getText().length() >= 8) {
            if (jPasswordContra.getText().length() <= 50) {
                if (jPasswordContra.getText().matches("[[A-Z]+[a-z]+[0-9]+[!|#|$|&|=|?|¿|+|-|*|-|_]+]+")) {
                   // if (jPasswordContra.getText().matches("[a-z]+")) {
                     //   if (jPasswordContra.getText().matches("[0-9]+")) {
                      //      if (jPasswordContra.getText().matches("[!|#|$|&|=|?|¿|+|-|*|-|_]+")) {
                                return true;
                       //     } else {
                      //          JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Contraseña\" Al Menos Uno De Los Siguientes Caracteres:\n! # $ & = ? ¿ + - * - _", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                      //          return false;
                      //      }
                       // } else {
                       //     JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Contraseña\" Debe Contener Al Menos Un Numero", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                       //     return false;
                       // }
                    //} else {
                    //    JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Contraseña\" Debe Contener Al Menos Una Letra Minuscula", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    //    return false;
                    //}
                } else {
                    JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Contraseña\" Debe Contener Al Menos Una Letra Mayuscula, Una Letra Minuscula, Un Numero y Un Caracter Especial", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Contraseña\" No Debe Contener Mas de 50 Caracteres", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Contraseña\" Debe Tener Como Minimo 8 Caracteres", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validarTipoDocu() {
        if (jComboBoxTipoDocu.getSelectedIndex() != 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: Debe Seleccionar Un Tipo De Documento", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validarNumeroDocu() {
        if (jTextFieldNumDocu.getText().length() > 0) {
            if (jTextFieldNumDocu.getText().length() <= 9) {
                if (jTextFieldNumDocu.getText().matches("[0-9]+")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Numero de Documento\" Debe Contener Solo Numeros", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Numero de Documento\" No Debe Contener Mas de 9 Numeros", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Numero de Documento\" No Debe Estar Vacio", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean validarTipoUsuario() {
        if (jComboBoxTipoUsu.getSelectedIndex() != 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: Debe Seleccionar Un Tipo De Usuario", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void jComboBoxTipoDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDocuActionPerformed

    private void jPasswordContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordContraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxTipoDocu;
    private javax.swing.JComboBox jComboBoxTipoUsu;
    private javax.swing.JLabel jLabeContra;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelIdUsu;
    private javax.swing.JLabel jLabelIdUsuario;
    private javax.swing.JLabel jLabelNombApe;
    private javax.swing.JLabel jLabelNombUsu;
    private javax.swing.JLabel jLabelNroDocu;
    private javax.swing.JLabel jLabelTipoDocu;
    private javax.swing.JLabel jLabelTipoUsu;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPasswordField jPasswordContra;
    private javax.swing.JTextField jTextFieldNombApe;
    private javax.swing.JTextField jTextFieldNombUsu;
    private javax.swing.JTextField jTextFieldNumDocu;
    // End of variables declaration//GEN-END:variables
}
