/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Leandro
 */
public class VentanaFacturacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFacturacion
     */
    public VentanaFacturacion() {
        initComponents();
        setLocationRelativeTo(null); //Centra la Ventana en la Pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneContenedor = new javax.swing.JScrollPane();
        jPanelContenedorFactura = new javax.swing.JPanel();
        jPanelLogo = new javax.swing.JPanel();
        jPanelTipoFactura = new javax.swing.JPanel();
        jLabelFechaFactura = new javax.swing.JLabel();
        jLabelNroFacturaFactura = new javax.swing.JLabel();
        jLabelTituloFactura = new javax.swing.JLabel();
        jLabelResponsableFactura = new javax.swing.JLabel();
        jPanelDatosCliente = new javax.swing.JPanel();
        jLabelNomApeClienteFactura = new javax.swing.JLabel();
        jLabelDomicilioFactura = new javax.swing.JLabel();
        jLabelTelefonoFactura = new javax.swing.JLabel();
        jLabelZonaFactura = new javax.swing.JLabel();
        jPanelDetalle = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDetalle = new javax.swing.JTable();
        jLabelTotal = new javax.swing.JLabel();
        jLabelPeso1 = new javax.swing.JLabel();
        jLabelImporteEnvioFactura = new javax.swing.JLabel();
        jLabelTotalFactura = new javax.swing.JLabel();
        jLabelPeso2 = new javax.swing.JLabel();
        jLabelPeso3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelResponsableFactura1 = new javax.swing.JLabel();
        jLabelCUIT = new javax.swing.JLabel();
        jLabelIVA = new javax.swing.JLabel();
        jLabelDomicilioLocal = new javax.swing.JLabel();
        jLabelTelefonoLocal = new javax.swing.JLabel();
        jLabelTituloComprobante = new javax.swing.JLabel();
        jLabelNombreApeCadete = new javax.swing.JLabel();
        jLabelNroCadete = new javax.swing.JLabel();
        jPanelDatosClienteComprobante = new javax.swing.JPanel();
        jLabelNombreYApellidoComprobante = new javax.swing.JLabel();
        jLabelDomicilioComprobante = new javax.swing.JLabel();
        jLabelNumFacturaComprobante = new javax.swing.JLabel();
        jLabelZonaComprobante = new javax.swing.JLabel();
        jLabelImporteEnvioComprobante = new javax.swing.JLabel();
        jLabelImporteFacturaComprobante = new javax.swing.JLabel();
        jLabelImporteTotalComprobante = new javax.swing.JLabel();
        jLabelPeso4 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));

        jScrollPaneContenedor.setMaximumSize(new java.awt.Dimension(740, 500));
        jScrollPaneContenedor.setMinimumSize(new java.awt.Dimension(740, 500));
        jScrollPaneContenedor.setPreferredSize(new java.awt.Dimension(740, 500));

        jPanelContenedorFactura.setMaximumSize(new java.awt.Dimension(720, 950));
        jPanelContenedorFactura.setMinimumSize(new java.awt.Dimension(720, 950));
        jPanelContenedorFactura.setPreferredSize(new java.awt.Dimension(720, 950));

        jPanelLogo.setBackground(new java.awt.Color(255, 0, 0));
        jPanelLogo.setMaximumSize(new java.awt.Dimension(280, 80));
        jPanelLogo.setMinimumSize(new java.awt.Dimension(280, 80));

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelTipoFactura.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanelTipoFacturaLayout = new javax.swing.GroupLayout(jPanelTipoFactura);
        jPanelTipoFactura.setLayout(jPanelTipoFacturaLayout);
        jPanelTipoFacturaLayout.setHorizontalGroup(
            jPanelTipoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        jPanelTipoFacturaLayout.setVerticalGroup(
            jPanelTipoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabelFechaFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelFechaFactura.setText("Fecha:");

        jLabelNroFacturaFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNroFacturaFactura.setText("Nro de Factura:");

        jLabelTituloFactura.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabelTituloFactura.setText("Factura");

        jLabelResponsableFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelResponsableFactura.setText("Nombre del Responsable");

        jPanelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanelDatosCliente.setMaximumSize(new java.awt.Dimension(700, 80));
        jPanelDatosCliente.setMinimumSize(new java.awt.Dimension(700, 80));
        jPanelDatosCliente.setPreferredSize(new java.awt.Dimension(700, 80));

        jLabelNomApeClienteFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNomApeClienteFactura.setText("Nombre y Apellido:");

        jLabelDomicilioFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDomicilioFactura.setText("Domicilio:");

        jLabelTelefonoFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTelefonoFactura.setText("Telefono:");

        jLabelZonaFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelZonaFactura.setText("Zona:");

        javax.swing.GroupLayout jPanelDatosClienteLayout = new javax.swing.GroupLayout(jPanelDatosCliente);
        jPanelDatosCliente.setLayout(jPanelDatosClienteLayout);
        jPanelDatosClienteLayout.setHorizontalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDomicilioFactura)
                    .addComponent(jLabelNomApeClienteFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZonaFactura)
                    .addComponent(jLabelTelefonoFactura))
                .addGap(151, 151, 151))
        );
        jPanelDatosClienteLayout.setVerticalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelTelefonoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelZonaFactura))
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelNomApeClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDomicilioFactura)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanelDetalle.setMaximumSize(new java.awt.Dimension(700, 300));
        jPanelDetalle.setMinimumSize(new java.awt.Dimension(700, 300));
        jPanelDetalle.setPreferredSize(new java.awt.Dimension(700, 300));

        jTableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio Unitario", "Total Linea"
            }
        ));
        jTableDetalle.setMaximumSize(new java.awt.Dimension(680, 285));
        jTableDetalle.setMinimumSize(new java.awt.Dimension(680, 285));
        jTableDetalle.setPreferredSize(new java.awt.Dimension(680, 285));
        jScrollPane3.setViewportView(jTableDetalle);

        jLabelTotal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTotal.setText("IMPORTE TOTAL DE FACTURA:");

        jLabelPeso1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabelPeso1.setText("$");

        javax.swing.GroupLayout jPanelDetalleLayout = new javax.swing.GroupLayout(jPanelDetalle);
        jPanelDetalle.setLayout(jPanelDetalleLayout);
        jPanelDetalleLayout.setHorizontalGroup(
            jPanelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetalleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPeso1)
                .addGap(167, 167, 167))
        );
        jPanelDetalleLayout.setVerticalGroup(
            jPanelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalleLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPeso1))
                .addContainerGap())
        );

        jLabelImporteEnvioFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImporteEnvioFactura.setText("Tarifa de Envio:");

        jLabelTotalFactura.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTotalFactura.setText("IMPORTE TOTAL:");

        jLabelPeso2.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabelPeso2.setText("$");

        jLabelPeso3.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabelPeso3.setText("$");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator1.setMaximumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(700, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(700, 10));

        jLabelResponsableFactura1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelResponsableFactura1.setText("Casa de Comidas EL PRINCIPITO");

        jLabelCUIT.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCUIT.setText("CUIT: 9999999999");

        jLabelIVA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelIVA.setText("IVA Responsable Inscripto");

        jLabelDomicilioLocal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDomicilioLocal.setText("Domicilio:");

        jLabelTelefonoLocal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTelefonoLocal.setText("Telefono:");

        jLabelTituloComprobante.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabelTituloComprobante.setText("Comprobante de Envio para el Cadete");

        jLabelNombreApeCadete.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombreApeCadete.setText("Nombre Y Apellido:");

        jLabelNroCadete.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNroCadete.setText("Cadete Nro:");

        jPanelDatosClienteComprobante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanelDatosClienteComprobante.setMaximumSize(new java.awt.Dimension(700, 150));
        jPanelDatosClienteComprobante.setMinimumSize(new java.awt.Dimension(700, 150));
        jPanelDatosClienteComprobante.setPreferredSize(new java.awt.Dimension(700, 150));

        jLabelNombreYApellidoComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombreYApellidoComprobante.setText("Nombre y Apellido:");

        jLabelDomicilioComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDomicilioComprobante.setText("Domicilio:");

        jLabelNumFacturaComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNumFacturaComprobante.setText("Nro de Factura:");

        jLabelZonaComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelZonaComprobante.setText("Zona:");

        jLabelImporteEnvioComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImporteEnvioComprobante.setText("Importe de Envio:");

        jLabelImporteFacturaComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImporteFacturaComprobante.setText("Importe de Factura:");

        jLabelImporteTotalComprobante.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImporteTotalComprobante.setText("IMPORTE TOTAL:");

        jLabelPeso4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabelPeso4.setText("$");

        javax.swing.GroupLayout jPanelDatosClienteComprobanteLayout = new javax.swing.GroupLayout(jPanelDatosClienteComprobante);
        jPanelDatosClienteComprobante.setLayout(jPanelDatosClienteComprobanteLayout);
        jPanelDatosClienteComprobanteLayout.setHorizontalGroup(
            jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDomicilioComprobante)
                    .addComponent(jLabelNombreYApellidoComprobante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZonaComprobante)
                    .addComponent(jLabelNumFacturaComprobante))
                .addGap(151, 151, 151))
            .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                        .addComponent(jLabelImporteEnvioComprobante)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                        .addComponent(jLabelImporteFacturaComprobante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelImporteTotalComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPeso4)
                        .addGap(189, 189, 189))))
        );
        jPanelDatosClienteComprobanteLayout.setVerticalGroup(
            jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                        .addComponent(jLabelNumFacturaComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelZonaComprobante))
                    .addGroup(jPanelDatosClienteComprobanteLayout.createSequentialGroup()
                        .addComponent(jLabelNombreYApellidoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDomicilioComprobante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImporteEnvioComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteComprobanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelImporteTotalComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPeso4))
                    .addComponent(jLabelImporteFacturaComprobante))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelContenedorFacturaLayout = new javax.swing.GroupLayout(jPanelContenedorFactura);
        jPanelContenedorFactura.setLayout(jPanelContenedorFacturaLayout);
        jPanelContenedorFacturaLayout.setHorizontalGroup(
            jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTituloFactura)
                                .addGap(103, 103, 103))
                            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNroFacturaFactura)
                                    .addComponent(jLabelFechaFactura))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                                .addComponent(jLabelResponsableFactura1)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelIVA))
                            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCUIT)
                                    .addComponent(jLabelResponsableFactura))
                                .addGap(141, 141, 141)
                                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefonoLocal)
                                    .addComponent(jLabelDomicilioLocal)))))
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabelImporteEnvioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabelTituloComprobante))
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelNroCadete)
                        .addGap(168, 168, 168)
                        .addComponent(jLabelNombreApeCadete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorFacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addComponent(jLabelTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPeso3)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addComponent(jPanelDatosClienteComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jPanelContenedorFacturaLayout.setVerticalGroup(
            jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContenedorFacturaLayout.createSequentialGroup()
                        .addComponent(jLabelTituloFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFechaFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNroFacturaFactura))
                    .addComponent(jPanelTipoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResponsableFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDomicilioLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResponsableFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefonoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jPanelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeso2)
                    .addComponent(jLabelImporteEnvioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPeso3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTituloComprobante)
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNroCadete)
                    .addComponent(jLabelNombreApeCadete, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosClienteComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPaneContenedor.setViewportView(jPanelContenedorFactura);

        jButtonCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonImprimir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-Imprimir.png"))); // NOI18N
        jButtonImprimir.setText("Imprimir Factura");
        jButtonImprimir.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonImprimir.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonImprimir.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPaneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JLabel jLabelCUIT;
    private javax.swing.JLabel jLabelDomicilioComprobante;
    private javax.swing.JLabel jLabelDomicilioFactura;
    private javax.swing.JLabel jLabelDomicilioLocal;
    private javax.swing.JLabel jLabelFechaFactura;
    private javax.swing.JLabel jLabelIVA;
    private javax.swing.JLabel jLabelImporteEnvioComprobante;
    private javax.swing.JLabel jLabelImporteEnvioFactura;
    private javax.swing.JLabel jLabelImporteFacturaComprobante;
    private javax.swing.JLabel jLabelImporteTotalComprobante;
    private javax.swing.JLabel jLabelNomApeClienteFactura;
    private javax.swing.JLabel jLabelNombreApeCadete;
    private javax.swing.JLabel jLabelNombreYApellidoComprobante;
    private javax.swing.JLabel jLabelNroCadete;
    private javax.swing.JLabel jLabelNroFacturaFactura;
    private javax.swing.JLabel jLabelNumFacturaComprobante;
    private javax.swing.JLabel jLabelPeso1;
    private javax.swing.JLabel jLabelPeso2;
    private javax.swing.JLabel jLabelPeso3;
    private javax.swing.JLabel jLabelPeso4;
    private javax.swing.JLabel jLabelResponsableFactura;
    private javax.swing.JLabel jLabelResponsableFactura1;
    private javax.swing.JLabel jLabelTelefonoFactura;
    private javax.swing.JLabel jLabelTelefonoLocal;
    private javax.swing.JLabel jLabelTituloComprobante;
    private javax.swing.JLabel jLabelTituloFactura;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalFactura;
    private javax.swing.JLabel jLabelZonaComprobante;
    private javax.swing.JLabel jLabelZonaFactura;
    private javax.swing.JPanel jPanelContenedorFactura;
    private javax.swing.JPanel jPanelDatosCliente;
    private javax.swing.JPanel jPanelDatosClienteComprobante;
    private javax.swing.JPanel jPanelDetalle;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelTipoFactura;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneContenedor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDetalle;
    // End of variables declaration//GEN-END:variables
}
